CREATE TABLE permissao (
  codigo bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO permissao (nome) VALUES ('CADASTRAR_PROPRIETARIO');
INSERT INTO permissao (nome) VALUES ('PESQUISAR_PROPRIETARIO');
INSERT INTO permissao (nome) VALUES ('CADASTRAR_IMOVEL');
INSERT INTO permissao (nome) VALUES ('PESQUISAR_IMOVEL');
INSERT INTO permissao (nome) VALUES ('CADASTRAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('PESQUISAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('GERAR_BOLETO');
INSERT INTO permissao (nome) VALUES ('DASHBOARD');